apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.fullname }}-service"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    app: {{ .Values.fullname }}
