---
- hosts: all
  become: true
  tasks:
  - name: Install Monitoring System
    command: "{{ item }}"
    with_items:
      - kubectl apply -k github.com/premist/k3s-kube-prometheus/setup
      - kubectl apply -k github.com/premist/k3s-kube-prometheus

  - name: Install ArgoCD
    shell: |
      kubectl create namespace argocd
      kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

  - name: Install ArgoCD Cli
    command: "{{ item }}"
    with_items:
      - VERSION=$(curl --silent "https://api.github.com/repos/argoproj/argo-cd/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
      - ARGOCD_SERVER_PORT=$(kubectl get svc argocd-server -n argocd)
      - curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/$VERSION/argocd-linux-amd64
      - chmod +x /usr/local/bin/argocd
      - export ARGOCD_PASSWORD=`kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d`
      - argocd login localhost:$ARGOCD_SERVER_PORT
      - argocd account update-password

  - name: Build Deployment
    shell: |
      argocd app create test --repo https://github.com/shdkej/space.git --path base --dest-server https://kubernetes.default.svc --dest-namespace default
