name: CD
on:
  push:
    branches: [ master ]
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get master IP
        run: echo "MASTER_IP=$(cat infra-k3s-setup/master_ip)" >> $GITHUB_ENV

      - name: "Sync ArgoCD"
        uses: omegion/argocd-app-actions@master
        with:
          address: 174.138.29.14:31598
          token: ${{ secrets.ARGOCD_TOKEN }}
          appName: "test"
