apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reel-room
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "2100m"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - reel.oracle.shdkej.com
      secretName: reel-room-tls
  rules:
    - host: reel.oracle.shdkej.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reel-room
                port:
                  number: 80
